language: ruby

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.8.0

env:
  - JAVA_OPTS="-Xms512m -Xmx2048m -Xss2048k -XX:G1HeapRegionSize=4m -XX:+UseG1GC -XX:+UseCodeCacheFlushing -Dfile.encoding=UTF-8 -Djruby.compile.invokedynamic=false -Djruby.global.require.lock=true -Djruby.thread.pool.enabled=true"

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.2.gemfile

notifications:
  email: false

bundler_args: --without development

services:
  - mongodb

sudo: false

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
