default_options: &default_options
  :w:                           1
  :pool_size:                   5
  :pool_timeout:                5
  :connect_timeout:             5
  :reconnect_attempts:          53
  :reconnect_retry_seconds:     0.1
  :reconnect_retry_multiplier:  2
  :reconnect_max_retry_seconds: 5
  :read:                        :nearest

test:
  uri: mongodb://localhost:27017/rocket_job_mission_control
  options:
    <<: *default_options
